### ISSUE TITLE
Should compare full namespace names

### ISSUE THREAD

**Issue by Sideboard** [zioth/dokuwiki-autolink4#12]
Currently, a link restricted to a namespace `ns1` may also appear in namespace `ns10` or `ns1a` since the comparison is only based on the start of the page namespace (`syntax/regex.php`):

```php
function _inNS($ns, $test) {
    $len = strlen($test);
     // namespace $ns is cut down to restriction length $len before comparison
    return !$len || substr($ns, 0, $len) == $test; 
}
```

I would expect that the restriction is strictly based on full namespace names, not substrings.

**Comment by zioth** [comment]
Weird. I'll try to create a work-around, but I probably won't have time for a couple weeks at least. Feel free to bug me if I forget!

**Comment by zioth** [comment]
I've fixed this to work as intended: Full namespace names are used, but sub-namespaces are always included (there's still no way to require an exact namespace but not its children). Examples:
* 'abc:d' is in 'abc'
* 'abc:de' is no longer in 'abc:d'
