### ISSUE TITLE
Option for case insensitive match

### ISSUE THREAD

**Issue by dgy18787** [zioth/dokuwiki-autolink4#13]
Hello,

Thank you for developing this convenient plugin. I wonder if there is a possible way to enable a case-insensitive global match, like "five hundred miles" would match "Five Hundred Miles", "FiVE huNDred mILES", and other various cases.

I have read the code and found on regex.php:78 seems to be the line that should be modified to achieve that. But I also noticed that the regex and non-regex seem to be parsed separately. Seems it needs to enable the case-insensitive feature for the DOKU_Lexer but I don't know how to deal with it. Could you kindly give some hints on that?

Thank you!

**Comment by zioth** [comment]
DokuWiki merges all plugin regexes into one giant regex. This makes flags like `/i` (case insensitivity) unavailable. However, the square bracket symbol still works, which means "one of these." In your case, you can capture the most common cases with:
```
[fF]ive [hH]undred [mM]iles
```
