### ISSUE TITLE
Different namespaces ignored for the same pattern

### ISSUE THREAD

**Issue by pparik** [zioth/dokuwiki-autolink4#14]
I use the Translation plugin, so the pages have the same name except for the root namespace (cs: or en:). I have configured the Auto Link plugin to create links to the appropriate translation like this:
```
name\.i1, cs:ref:name:i1, cs
name\.i1, en:ref:name:i1, en
```
but this _always_ creates links to `cs:ref:name:i1`, even in `en` namespace. If I switch the two lines, then all links are created to `en:ref:name:i1`. So there is clearly a bug with duplicate patterns where the page name in the _first_ pattern+namespace definition is used regardless of the actually _matched_ pattern+namespace definition.

**Comment by zioth** [comment]
Interesting. It might take some time for me to get to this. If you don't hear from me after a while, feel free to bug me again by adding a comment to this issue.

**Comment by zioth** [comment]
Fixed! The plugin should now work when you have the same pattern in two namespaces.

In the future, I might consider adding more direct translation plugin compatibility, so you don't have to include the same pattern multiple times.

**Comment by pparik** [comment]
Thank you! Updated and working :)
