### ISSUE TITLE
Didn't work with Autotooltip since the last update

### ISSUE THREAD

**Issue by Dirk-27** [zioth/dokuwiki-autolink4#18]
We use autolink4 together with autotooltip (https://www.dokuwiki.org/plugin:autotooltip) and we updated autolink4 and the translation plugin (https://www.dokuwiki.org/plugin:translation) today. The links are correct but the autotooltip shows always the first glossary entry. Before the update it worked like specified.

Note: in the translation plugin we use the first way: 'a default language in the root namespace and translations in sub namespaces'

Here is our configuration for autolink4:
```
Anklicken, :glossary#anklicken, , tt
[Cc]lick|[Cc]licking, :en:glossary#click, en, tt

Asset[s]?, :glossary#asset, , tt
Asset[s]?, :en:glossary#asset, en, tt

Cardboard-Modus, :glossary#cardboard-modus, , tt
[Cc]ardboard mode, :en:glossary#cardboard-modus, en, tt

Macher, :glossary#macher, , tt
[Mm]aker, :en:glossary#maker, en, tt

```

**Comment by zioth** [comment]
I see that you have a version with no namespace, then a version with the "en" namespace. Is the problem that you get the default version, even in the "en" namespace?

I haven't tried that configuration myself. Removing the default option and specifying all namespaces should work for now, and I'll see when I can get to an actual fix. Feel free to bug me if it doesn't happen in a week or so.

**Comment by Dirk-27** [comment]
I see that you have a version with no namespace, then a version with the "en" namespace. Is the problem that you get the default version, even in the "en" namespace?

Yes, the problem exists in both namespaces. As you can see in the code, the tooltip content didn't show the correct caption from the glossary. The link (`/doku.php?id=en:glossary#maker`) is correct but the content of the `span `with class `plugin-autotooltip-hidden-tip` is not.

```
<span class="plugin-autotooltip_linked" onmouseover="autotooltip.show(event)" onmouseout="autotooltip.hide()" data-delay="0">
  <a href="/doku.php?id=en:glossary#maker" class="wikilink1" data-wiki-id="en:glossary">Maker</a>
  <span class="plugin-autotooltip-hidden-classes">plugin-autotooltip__default plugin-autotooltip_big</span>
  <!-- googleoff: all -->
  <span class="plugin-autotooltip-hidden-tip">
    <span class="plugin-autotooltip-title">Glossary</span>
    <br><br>Asset<br><br>
    All content that is created by users and made available via the platform is called an asset. Examples of assets are:<br>
    <br> * 3D models * 360 degree panoramas * Textures<br><br>
    Cardboard Mode<br><br>
    Cardboard mode (also called Magic Window) is activated on smartphones when the VR button is pressed. If the VR button is 
  not visible, then it is not possible to switch to VR mode because the hardware does not allow this.
  </span>
  <!-- googleon: all -->
</span>

```

Perhaps this problem is only related to autotooltip in combination with the translation plugin update?

**Comment by Dirk-27** [comment]
The workaround for us is to disable the autotooltip plugin.

**Comment by zioth** [comment]
I think I misunderstood your problem. The link is in the "en" namespace and the tooltip content is in English. What do you expect it to be?

I've never actually used the translation plugin myself, so I'm not sure what's expected here.

**Comment by Dirk-27** [comment]
Before the updates the tooltip in the popup shows the section where the link points to (in my example: glossary#maker). So the content starts with `<br><br>Maker<br><br>`.

After the update  the tooltip in the popup shows allways the first glossary section (in my example: glossary#asset). . So the content starts with `<br><br>Asset<br><br>`, which is wrong.

**Comment by Dirk-27** [comment]
I have carried out tests with a deactivated translation plugin. The problem remains.

**Comment by zioth** [comment]
I understand now. Thanks.

I'm kind of surprised this worked before, since DokuWiki doesn't normally store abstracts for sections. Did you update any other plugins at the same time? Did you update DokiWiki?

**Comment by Dirk-27** [comment]
What we see in the autotooltip popup  is not an abstract for the section but the section itself. It is somehow copied from the linked page to appear here in the popup. Retrieving this page section content is broken. I remembered to have only an update of the two plugins autolink4 and translation. DokuWiki is was not updated. But as if translation can be disabled and the problem remains, it should be related to the autolink4 update.

**Comment by zioth** [comment]
Are you sure this ever worked?

I haven't updated autotooltip in years, and the code specifically ignores anchors (what comes after the #). The reason is that the tooltip comes from the page's abstract, and DokuWiki only stores an abstract for the whole page, not for each section.

Unfortunately, autotooltip isn't great for single-page glossaries, and adding support for sections would take a lot of work and slow down page edits. I'd have to ignore DokuWiki's abstracts and create my own metadata which was updated every time a page was changed. :(

**Comment by Dirk-27** [comment]
> Are you sure this ever worked?

Yes, I am! We just worked on the glossary and added the section on assets, and before the update every popup showed exactly the right section. After the update, we only see the first section (whatever that is) in the popups.

I'm sure it's intentional that the popup contains the section that the link points to, even if an anchor (#) is used. How else should 'tt' in autolink behave? Linking to an anchor on a page, but displaying the first section of the page in a popup is not what the user wants.

I took a quick look at the commits, but I don't know php that well. Maybe the change is related to a change in helper.php, like here: https://github.com/zioth/dokuwiki-autolink4/commit/c8ba145b134bd92915084043bf921a13592e4b80 ?

Can you (or we) try older versions of autolink4 to show that the behavior was different with an older version?

**Comment by zioth** [comment]
Just tried a four-year-old version, and I still only see the top section in the tooltip. I also went through the autotooltip code one more time, and it's been ignoring anchors for the last 6 years. Before that, anchors caused a blank tooltip to be displayed. DokuWiki has never supported the behavior you're describing, so I'm very confused that you say it worked before (to clarify, autotooltip uses built-in Doku functionality to get the content of the tooltip).

Do you happen to remember when you last updated autotooltip and autolink4? I don't see how this could ever have worked, but I'm willing to play around with it a little more.

> Linking to an anchor on a page, but displaying the first section of the page in a popup is not what the user wants.

I agree with you that many or most users would want tooltips to include anchor text, but given that I do this for fun in my spare time, I unfortunately can't do everything users want. :)

**Comment by Dirk-27** [comment]
Believe me, it worked. I showed it to a teammate early in the morning before the update of autolink4 the day I opened this issue.

The problem can't be related to autotooltip because it hasn't changed, so I'm pretty sure it's related to autolink4.

What code is responsible for getting the section for an anchor when we add `, tt` to the autolink4 configuration? Have some regexp changed or was there a change in looking up a map or dictionary perhaps?

I think the autolink4 plugin was max. 1 year old before we updated it on 2nd of January. Our Dokuwiki installation is about two years old, but we've been using the latest version for 3 months.

Is there something like an update log in dokuwiki?

**Comment by zioth** [comment]
Still haven't been able to figure this out, and there's a reported issue from two years ago (in autotooltip) where someone requests the feature you're describing - https://github.com/zioth/dokuwiki-autotooltip/issues/18

I just have no idea how this could ever have worked for you. Have you tried an earlier version of the plugin?

For reference, here's the line in autotooltip where it explicitly ignores hashes (page sections) - https://github.com/zioth/dokuwiki-autotooltip/blob/master/helper.php#L179

Removing that line results in blank tooltips, because `p_get_metadata` (a core dokuwiki function) doesn't support `#`.

**Comment by Dirk-27** [comment]
We were also unable to reproduce the display of the sections referenced via #. The code does not seem to allow it either. In the meantime, we have helped ourselves by creating one page per glossary entry. Perhaps you can point out in the documentation that it is possible to reference headings with # for headings (anchors), but with the tt feature these are then not displayed in the popups?

**Comment by zioth** [comment]
Good idea. I've added a note to the docs.
