### ISSUE TITLE
No Chinese Support

### ISSUE THREAD

**Issue by IanGoo** [zioth/dokuwiki-autolink4#2]
I tried but lines written in Chinese does not work, while in Latin characters the plugin works.

Anything to do to solve the problem?

**Comment by zioth** [comment]
This should be solvable. I'm not very familiar with Chinese. Are there spaces between words? If not, that could be the cause.

**Comment by IanGoo** [comment]
> 
> 
> This should be solvable. I'm not very familiar with Chinese. Are there spaces between words? If not, that could be the cause.

Nope. There's no space.

I also tested Japanese, Korean and ... Arabic. It seems that non of these non-latin texts are supported.

Maybe try to encode them into URL or UTF? Depend on the setting of non-ASCII filename encoding. As DokuWiki actually read files based on their names, the filename of a Chinese-named page will be encoded into URL or UTF-8 to make sure that it can be read. 

For example, if I set the encoding to `URL` and then created a page named "发动机“(in Eng it means **engine**), the file name in server will be `%e5%8f%91%e5%8a%a8%e6%9c%ba.txt`。

I'm not a developer, just a suggestion based on my knowledge.

**Comment by shaokuan101** [comment]
Yes, I would be very happy to see Autolink4 supports Chinese.

**Comment by idealclover** [comment]
Would be happy to see, too.

**Comment by GJRobert** [comment]
+1 for non-ASCII support~~~

**Comment by GJRobert** [comment]
Could the problem be with the regex finder DokuWiki is using?

**Comment by zioth** [comment]
GJRobert, I think you're right. This looks to be a bug in DokuWiki: https://github.com/splitbrain/dokuwiki/issues/856 (also see https://bugs.dokuwiki.org/2947.html).

After messing with it for an hour, I wasn't able to find a fix. I tried hex-escaping the UTF-8 characters in `helper.php` like this:
```
$orig = '\\x' . implode('\\x', str_split(implode('', unpack('H*', $orig)), 2))
```
and it didn't help. However, changing `getPerlMatchingFlags` in `/inc/Parsing/Lexer/ParallelRegex.php` worked:
```
    protected function getPerlMatchingFlags()
    {
        return ($this->case ? "umsS" : "umsSi");
    }
```
I'll do a little more investigation. In the mean time, you can add support by making the change to Doku core code yourself.

**Comment by zioth** [comment]
I've added a comment to the dokuwiki ticket: https://github.com/splitbrain/dokuwiki/issues/856

**Comment by GJRobert** [comment]
Thanks for the insight @zioth 

I have tried the method below:
> However, changing `getPerlMatchingFlags` in `/inc/Parsing/Lexer/ParallelRegex.php` worked:
> 
> ```
>     protected function getPerlMatchingFlags()
>     {
>         return ($this->case ? "umsS" : "umsSi");
>     }
> ```
But autolink4 does not seem to convert my Unicode strings. I guess there might be something I'm missing...
(other ASCII strings are converted)

**Comment by zioth** [comment]
From what I understand (as someone who neither speaks nor reads Chinese), two words in Chinese can be pressed up against each other without any space between. If that's true, that could be the cause of the problem, because DokuWiki's regular expression parser doesn't take that into account. I might be able to fix it by adding a special setting for Chinese and similar languages.

Could you post the autolink4 configuration line you're using, and a short piece of sample content including the word that's not working? I might be able to figure something out.

**Comment by GJRobert** [comment]
Thanks a lot. Here is my autolink4 config:
```
巧皇后, family:queen, , tt|once
我, :me, , tt|once
```

And sample article:
```
今天全家人（我請特休），和其他 3 個家庭約好去麗寶樂園，玩得真的挺開心的（雖然受限於小孩要午睡，能玩的時間很短）。午餐時我用筆電處理工作，聽到旁邊 5 歲的吾兒飯後吵著叫巧皇后買霜淇淋給他，結果一支還挺大的。
```

**Comment by zioth** [comment]
It's finally fixed. :) In addition to making the change to core Doku code, you'll have to set the new `inword` flag on every Chinese string in the config. This will allow for words that are not surrounded by spaces (DokuWiki's regular expression parser assumes words are always surrounded by spaces or punctuation).

**Comment by GJRobert** [comment]
Yes! **2020-10-25 + DW core code modification** working for my non-Latin strings now. Thanks a million for your support!!!
