### ISSUE TITLE
Not always desirable: "Don't autolink references to the current page"

### ISSUE THREAD

**Issue by chlarsen** [zioth/dokuwiki-autolink4#5]
Greetings!
I just encountered a use case, where I have a fairly long wiki page with headings and sub-headings, as well as anchors, and where autolinks to contents in the SAME page would be highly appropriate.
Therefore, the above code is a bit counter-productive. Maybe whether or not to set autolinks in the same page should be a configuration option, ideally per namespace?
I have reverted the edits to https://github.com/zioth/dokuwiki-autolink4/commit/0c0a5b58900d3fbd7a8bfc0092922e5be17cb379#commitcomment-34915122 as follows, taking into account your code re-factoring:
In file **./lib/plugins/autolink4/helper.php**:
``````
                                        // Check that it's in the right namespace, and skip links to the current page
                                        //if (strlen($data[self::$ORIG]) && strlen($data[self::$TO])) {
                                        // Check that it's in the right namespace
                                        if (strlen($data[self::$ORIG])) {
``````
In file **./lib/plugins/autolink4/syntax/regex.php**:
``````
                        // Check that it's in the right namespace, and skip links to the current page.
                        //if ($this->_inNS($ns, $s[self::$IN]) && !$this->_isSamePage($s[self::$TO], $ID)) {
                        // Check that it's in the right namespace.
                        if ($this->_inNS($ns, $s[self::$IN])) {
``````
Kindly advise, if I made a mistake. Could this be configured via the admin panel instead, according to namespace-specific needs?
Thank you!
Chris

**Comment by zioth** [comment]
I'm not sure I understand your use case. Autolink4 doesn't link to _contents_ in the same page; it links to the page itself. That kind of link wouldn't do anything when clicked. If you want to link to contents (using a # symbol), you'll need a regular DokuWiki link. Am I missing something?

**Comment by chlarsen** [comment]
Thank you for replying so quickly. Actually, AutoLink4 DOES link t contents in the same page, it works like a charm. Here is a sample entry in the admin configuration table:
``````
[Nn]otifiable [Dd]isease, health:sops:manual:full#ihr_group_1_diseases, health:sops
``````
Creates a dynamic link that redirects exactly to the "IHR Group 1 Diseases" subheading. It therefore makes sense, not to disable reference within the _same_ page.
:-)

**Comment by zioth** [comment]
Oh, of course. :)

The correct fix is to have `_isSamePage` return false when there's a hash link involved. I'll try to get a fix in soon. While you're waiting, your revert should work fine for you.

**Comment by chlarsen** [comment]
Terrific, thank you! Hugely appreciated.
Warmest regards from Kenya.

**Comment by zioth** [comment]
Fixed

**Comment by chlarsen** [comment]
Works like a charm, thank you so much!
