### ISSUE TITLE
Link to section in page

### ISSUE THREAD

**Issue by shenzo1** [zioth/dokuwiki-autolink4#7]
Great plugin! It would be awesome to be able to link to sections in page in the format ns:page#section. 

Also another minor suggestion: to be able to use a list of terms like: [apples, oranges and bananas] as the expression to be searched for. Right now the use of commas is part of the syntax, but what about using ; instead?

In any case, great work!

**Comment by zioth** [comment]
A section link is a good idea, and not too hard to implement, I think.

As for your other suggestion, the terms list accepts regular expressions. Try this: `(apples|oranges|bananas)`

**Comment by shenzo1** [comment]
Thanks for considering my suggestion!

About the list, I meant the possibility to write a text to search like “apples, oranges and bananas”, with a comma included in a search text. I understand the use case might be limited but I work with a lot of terminologies that often come in trios like this. So to be able to use commas as part of an expression to search would be very useful to me. But again I understand it might require too many changes on other parts of your code that may not make it very relevant to you.

**Comment by zioth** [comment]
Ah, I get it. The code uses standard CSV parsing, so I believe putting the text in double quotes will work:
`"apples, oranges and bananas", other fields`

**Comment by shenzo1** [comment]
Oh that is great! Thank you!
